test:
	cls
	g++ -std=c++11 test.cpp -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 -o test.exe
	.\test.exe
	rm *.exe

main:
	cls
	g++ -std=c++11 main.cpp -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 -o main.exe
	.\main.exe
	rm *.exe

clean:
	rm *.exe
